#pragma once

#define SCREEN_WIDTH 1200
#define SCREEN_HEIGHT 800
#define FPS 60
#define SCREEN_TITLE "Triangle Following Mouse Example"
#define BG_COLOR WHITE

#define TRIANGLE_NUMBERS 200
#define TRIANGLE_SIZE 10
#define TRIANGLE_COLOR RED
#define TRIANGLE_INITIAL_MAX_VELOCITY 1
#define TRIANGLE_MAX_COLORS 7
#define TRIANGLE_ACCELERATION_FACTOR 3000
#define TRIANGLE_VELOCITY_FRICTION_FACTOR .99f
#define TRIANGLE_SEPARATION_FACTOR 10