#pragma once

#define SCREEN_WIDTH 1200
#define SCREEN_HEIGHT 800
#define FPS 60
#define SCREEN_TITLE "Raylib Window"
#define BG_COLOR WHITE

#define TRIANGLE_NUMBERS 100
#define TRIANGLE_SIZE 20
#define TRIANGLE_COLOR RED
#define TRIANGLE_INITIAL_MAX_VELOCITY 1
#define TRIANGLE_MAX_COLORS 7
#define TRIANGLE_ACCELERATION_FACTOR 2000
#define TRIANGLE_VELOCITY_FRICTION_FACTOR .99f